### Registro de un nuevo usuario

POST http://localhost:5000/signin
Content-Type: application/json

{
  "usuario": "nombre_de_usuario",
  "contrasena": "contraseña_del_usuario"
}

### Login de un usuario

POST http://localhost:5000/login
Content-Type: application/json

{
  "usuario": "nombre_de_usuario",
  "contrasena": "contraseña_del_usuario"
}

